#!/bin/bash

# Author: Daniel Kahn Gillmor <dkg@fifthhorseman.net>
# Date: 2009-10-08
# License: GPL v3+

set -e

# depends on grub2

# specify the first argument as the new installer image:

output="$1"

if [ -z "$output" ] ; then
    printf "you must specify a file name for the image to be built" >&2
    exit 1
fi

if [ -e "$output" ] ; then
    printf "file '%s' already exists" "$output" >&2
    exit 1
fi


WORKDIR=$(mktemp -d)

cleanup() {
    rm -rf "$WORKDIR"
}

trap cleanup EXIT

( cd "$WORKDIR" && wget http://ftp.nl.debian.org/debian/dists/lenny/main/installer-amd64/current/images/netboot/debian-installer/amd64/{linux,initrd.gz} )

mkdir -p "$WORKDIR/boot/grub"

cat > "$WORKDIR/boot/grub/grub.cfg" <<EOF
serial --unit=0 --speed=115200 --word=8 --parity=no --stop=1
terminal_output serial
terminal_input serial

menuentry "lenny d-i (created $(date -R))" {
  linux /linux verbose -- console=ttyS0,115200n8
  initrd /initrd.gz
}
EOF

## no longer using genisoimage with grub2:
# genisoimage -R -input-charset utf-8 -b boot/grub/stage2_eltorito -no-emul-boot --boot-load-size 4 -boot-info-table "$WORKDIR"

grub-mkrescue --overlay="$WORKDIR" "$output"
